source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RBSegmentedControl_Example', :exclusive => true do
  pod 'RBSegmentedControl', :path => '../'
end

target 'RBSegmentedControl_Tests', :exclusive => true do
  pod 'RBSegmentedControl', :path => '../'

  
end
